# Generated by Django 6.0.3 on 2026-05-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], default=1, verbose_name='Голос'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionlike',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], default=1, verbose_name='Голос'),
            preserve_default=False,
        ),
    ]
