services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:17
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  centrifugo:
    image: centrifugo/centrifugo:v5
    ports:
      - "8080:8080"
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    command: centrifugo --config /centrifugo/config.json

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped

  celery:
    build: .
    command: celery -A application worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celerybeat:
    build: .
    command: celery -A application beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pgdata:
  redisdata:
